version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FluentValidation
    versions:
    - 10.0.0
    - 10.0.1
    - 10.0.2
    - 10.0.3
    - 10.0.4
    - 9.4.0
    - 9.5.0
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
  - dependency-name: FatturaElettronica
    versions:
    - 3.1.1
    - 3.1.2
  - dependency-name: Microsoft.NETCore.Platforms
    versions:
    - 5.0.0
    - 5.0.1
